# Generated by Django 3.2.7 on 2023-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmodel',
            options={'verbose_name': 'Председатель', 'verbose_name_plural': 'Председатели'},
        ),
        migrations.AlterModelOptions(
            name='bankmodel',
            options={'verbose_name': 'Банковские реквизиты', 'verbose_name_plural': 'Банковские реквизиты'},
        ),
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': 'СНТ', 'verbose_name_plural': 'СНТ'},
        ),
        migrations.AlterModelOptions(
            name='debtsmodel',
            options={'verbose_name': 'Задолженность', 'verbose_name_plural': 'Задолженности'},
        ),
        migrations.AlterModelOptions(
            name='landmodel',
            options={'verbose_name': 'Земельный участок', 'verbose_name_plural': 'Земельные участки'},
        ),
        migrations.AlterModelOptions(
            name='paymentsmodel',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='penaltymodel',
            options={'verbose_name': 'Начисления', 'verbose_name_plural': 'Начисления'},
        ),
    ]
