# Generated by Django 3.2.7 on 2023-07-26 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230726_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermodel',
            old_name='divison_code',
            new_name='division_code',
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 8, 9, 32, 460971)),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 8, 9, 32, 460932)),
        ),
    ]
