# Generated by Django 3.2.7 on 2023-08-01 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230726_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 1, 4, 24, 23, 363610), null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_issue',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 1, 4, 24, 23, 363572), null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
