# Generated by Django 3.2.7 on 2023-08-14 03:17

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230801_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 14, 3, 17, 44, 642438), null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_issue',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 14, 3, 17, 44, 642399), null=True),
        ),
        migrations.AlterField(
            model_name='membersfeemodel',
            name='attachment',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
    ]
