# Generated by Django 3.2.7 on 2023-09-14 01:45

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230814_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 14, 1, 45, 57, 691453), null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_issue',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 14, 1, 45, 57, 691412), null=True),
        ),
        migrations.AlterField(
            model_name='scancompanymodel',
            name='inn',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='scancompanymodel',
            name='ogrn',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='scancompanymodel',
            name='ustav',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='scancompanymodel',
            name='yegryul',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
    ]
