# Generated by Django 3.2.7 on 2023-09-14 02:42

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230914_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='file_doc',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='landmodel',
            name='attachment',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 14, 2, 42, 52, 157522), null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='date_of_issue',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 14, 2, 42, 52, 157483), null=True),
        ),
        migrations.AlterField(
            model_name='ownershipmodel',
            name='attachment',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='attachment',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
    ]
